spring.application.name=TasfTravelControl


# URL de la base de datos (asegúrate de que la BD 'nombre_tu_db' ya exista en Postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/nombre_tu_db
spring.datasource.username=postgres
spring.datasource.password=tu_password_aqui

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect